services:
  postgres:
    image: postgres:16
    container_name: eduflow-postgres
    environment:
      POSTGRES_USER: eduflow
      POSTGRES_PASSWORD: eduflow_password
      POSTGRES_DB: eduflow
    ports:
      - "5434:5432"
    volumes:
      - eduflow_pg:/var/lib/postgresql/data
volumes:
  eduflow_pg: